[#3579] fix(license): mention license for svg files
datastrato/gravitino pull request #3617
Opened 2024-05-29 06:33 UTC by LauraXia123

### What changes were proposed in this pull request?

(Please outline the changes and how this PR fixes the issue.)

### Why are the changes needed?
mention license for svg files

Fix: #3579

### Does this PR introduce _any_ user-facing change?
N/A

### How was this patch tested?
N/A

2024-05-29 08:04 UTC, justinmclean commented
Am I misisng something? The files have changed but they are still not mentioned in the LICENSE file. Where are the new files from and how are they licensed?

2024-05-29 08:09 UTC, justinmclean requested changes
Still unknown where the files are from or what their license is. There has been no changes to the LICENSE file.

2024-05-29 12:12 UTC, jerryshao approved these changes

2024-05-30 02:04 UTC, merged

2024-05-30 04:44 UTC, justinmclean commented
This needs to be reverted. We legally can't add license headers to files without the permission of the copyright holder of those files. It s also not clear how those files are licensed.