[#3579] fix(license): mention license for svg files
datastrato/gravitino pull request #3635
Opened 2024-05-30 02:58 UTC by LauraXia123

### What changes were proposed in this pull request?
mention license for svg files

### Why are the changes needed?
mention license for svg files

Fix: #3579

### Does this PR introduce _any_ user-facing change?
N/A

### How was this patch tested?
N/A

2024-05-30 04:11 UTC, justinmclean requested changes
Again it is unclear where these come from and exactly how they are licensed. Please list the source of teh files so we can work this out.

2024-05-30 04:21 UTC, jerryshao commented
> Again it is unclear where these come from and exactly how they are licensed. Please list the source of teh files so we can work this out.

They are already listed in the license file.

2024-05-30 04:23 UTC, jerryshao commented
@justinmclean we don't want this to block our release, just show us exactly how to fix it, or we will leave as it is.

2024-05-30 05:15 UTC, jerryshao commented on web/src/lib/icons/svg/doris.svg
> +-->
@justinmclean  please check here.

2024-05-30 05:15 UTC, jerryshao commented
Talked with @LauraXia123 offline, we have already listed the source in the SVG file, you can check the source diffs of the these svg files. @justinmclean

2024-05-30 05:16 UTC, jerryshao commented
```
 *
 * Referred from Apache Doris's icon.svg implementation
 * https://github.com/apache/doris/blob/master/.idea/icon.svg
-->
```

2024-05-30 06:14 UTC, closed without merging

2024-05-31 04:59 UTC, justinmclean commented
The short version is that it is not clear how this is licensed and that content on a website doesn't have to be compatible with the ASF license as it has not gone through a release process. We can also not add or alter headers of files not created by us, to do that you need the owners permission.

2024-05-31 05:00 UTC, justinmclean commented
As discussed yesterday, I'll take a look at this today and propose a better solution.